### ISSUE TITLE
Couldn't initialize handshake 10 engine

### ISSUE THREAD

**Issue by jasonliu497** [jaw20/Crunchyroll-XML-Decoder#2]
Firstly thanks very much for taking over the project.
But it appears that crunchy roll has changed something again...

http://www.crunchyroll.com/jojos-bizarre-adventure/episode-37-shining-d-diamond-is-unbreakable-part-1-720857

Video failed to download, trying again. (3/3)
RTMPDump v2.5 GIT-2012-03-31 (Handshake 10 support by Xeebo)
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
ERROR: Couldn't initialize handshake 10 engine, exiting!

**Comment by jaw20** [comment]
Are you using the last build from the original project page? Or did you
re-download the files from here? There were some changes that I reverted
from the last commit, so if you didn't download this one there may be some
problems. Additionally it may be that the .swf link needs to be updated,
but if redownliading doesn't help then we'll go from there.

**Comment by jasonliu497** [comment]
This was downloaded from here, but I just checked again and this particular link is working. So it was probably a CR problem, all good now.
