### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by markk001** [jaw20/Crunchyroll-XML-Decoder#20]
Hello, I'm using Crunchyroll-XML-Decoder for the first time and I can not download any files.

I have 1 premium account and the program seems to work fine to the point.

When adding the link of the Episode appears the error that is in the image

![erro xml-decoder](https://cloud.githubusercontent.com/assets/27076611/24830234/fa670a6e-1c57-11e7-97a2-dfcd599c2917.jpg)

**Comment by alzamer2** [comment]
why do you open multi issue for the same error
like you did on #22

**Comment by markk001** [comment]
Ok, thanks, after installing Python 2.7.9 is working again.
