### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by markk001** [jaw20/Crunchyroll-XML-Decoder#22]
Once installed it appears this message when trying to download 1 episode

![erro3](https://cloud.githubusercontent.com/assets/27076611/24834251/19aa6df4-1cb6-11e7-9ddd-ae1e67e89965.jpg)

I think m3u8 is missing but I installed it as you explained here https://github.com/einstein95/crunchy-xml-decoder/issues/95 

And I have this result
![intalando m3u8-0 2 10](https://cloud.githubusercontent.com/assets/27076611/24834283/d3cc4662-1cb6-11e7-8ba0-ede9249f5f27.jpg)

What would be missing?

**Comment by markk001** [comment]
Ok, thanks, after installing Python 2.7.9 is working again.

**Comment by alzamer2** [comment]
if the problem solved close this issue and #20 
as the one who create them you can too
