### ISSUE TITLE
Erro download subtitles

### ISSUE THREAD

**Issue by markk001** [jaw20/Crunchyroll-XML-Decoder#27]
When you try to download the subtitles of this episode  http://www.crunchyroll.com/worldend-what-do-you-do-at-the-end-of-the-world-are-you-busy-will-you-save-us/episode-2-late-autumn-nights-dream-733677 this error appears

![erro subs](https://cloud.githubusercontent.com/assets/27076611/25144522/78b3b536-2444-11e7-8231-a0b0bc926ec8.jpg)

**Comment by alzamer2** [comment]
not sure why
i downloaded the same episode and no problem happen to me
try my code https://github.com/alzamer2/Crunchyroll-XML-Decoder and tell me what happen

**Comment by alzamer2** [comment]
sorry i did not notice that you want to download only subtitle
is the problem still there?

**Comment by markk001** [comment]
sim, o problema ainda continua

**Comment by alzamer2** [comment]
ok i tried full download and no problem with me
but u just noiced this the place you put the code has long path and the anime it self has long name so i think your problem is the same as issue #1 

i just recently worked ariund it and request pull for it, you can wait or go to my fork https://github.com/alzamer2/Crunchyroll-XML-Decoder and download fresh copy and try it out

**Comment by markk001** [comment]
I tried the two options that you gave me, but in both cases the same problem that you can see in the image.

ERROR Message: THE SPECIFIED PATH CAN NOT BE FOUND
![error instal](https://cloud.githubusercontent.com/assets/27076611/25626206/21d7f49c-2f35-11e7-8df5-d8d446ce08f3.jpg)

**Comment by markk001** [comment]
Remembering that the episode in .ts is downloaded, but subtitles are not downloadable

**Comment by alzamer2** [comment]
is this mt fork or from Jaw

jaw still did not merge my fix

**Comment by alzamer2** [comment]
i used path this long to test it out and it worked
C:\Users\********\Documents\GitHub\+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\Crunchyroll-XML-Decoder\

**Comment by markk001** [comment]
I tried to install, this version https://github.com/alzamer2/Crunchyroll-XML-Decoder but the error that appears in the image appears.

And also when having to use the patch here https://github.com/jaw20/Crunchyroll-XML-Decoder/issues/1

The same error happens

**Comment by alzamer2** [comment]
say can you try putting the code in root drive like C:\Crunchyroll-XML-Decoder or D:\Crunchyroll-XML-Decoder and post image for me

**Comment by markk001** [comment]
I put it in the unit and now it worked, before I was putting it in the folder. Which was inside the unit.

**Comment by alzamer2** [comment]
good to hear that
