### ISSUE TITLE
Background downloading

### ISSUE THREAD

**Issue by morocoeltopo** [jaw20/Crunchyroll-XML-Decoder#35]
For some reason the download gets paused if i let cmd on background, it resumes when i click on the windows again an focus on it. Im on W10 running the bat file.

**Comment by shinji257** [comment]
I've been unable to reproduce this issue.  Been running this script for a long while on Windows 10 including insider builds.

**Comment by jaw20** [comment]
Please reopen if you re-encounter the issue.
