### ISSUE TITLE
CSRF token not found?

### ISSUE THREAD

**Issue by starcipher** [jaw20/Crunchyroll-XML-Decoder#5]
I'm unable to log in. After I try to log in, the message "CSRF token not found" appears and then it closes. What should I do? I'm not sure if this is related, but no 'cookies' file was generated. Thanks.

**Comment by AhmadKahlid** [comment]
just put this in your \crunchy-xml-decoder\ directory and replace it, it should work
[login.zip](https://github.com/jaw20/Crunchyroll-XML-Decoder/files/680594/login.zip)

**Comment by starcipher** [comment]
Thank you! It works!

**Comment by jaw20** [comment]
@AhmadKahlid Is the fix you provided the same in the github? or Should I commit the new file?

**Comment by Limitless99** [comment]
@jaw20 it's not the same. "CSRF token not found" will occur.
You better replace "login" file to the one that @AhmedKahlid has provided!

**Comment by jaw20** [comment]
I will commit the changes asap.
