### ISSUE TITLE
Problem with the episodes titles

### ISSUE THREAD

**Issue by Teredic** [jaw20/Crunchyroll-XML-Decoder#51]
Hello,

I think Crunchyroll has changed something, based on the localisation, because... i don't have the episode title anymore in the mkv file.

I will give you an example... Before i was getting something like : 
- Katana Maidens ~ Toji No Miko Episode 4 - The Burden of Resolution[1080p].mkv

Now i get : 
- Katana Maidens ~ Toji No Miko Episode 4 - Regarder sur Crunchyroll[1080p].mkv

Please note that "Regarder sur Crunchyroll" is the french version of "Crunchyroll - Watch" tag.

For now i am changing the title by hand, but could you please update the code when you have time ?

Thanks in advance
-T.

edit : I just tried at random the episode 8 from Caligula... And the file name is "Redirecting.mkv"
It's strange.

**Comment by onimk** [comment]
find a solution:

on "decode.py"
just after  **soup = BeautifulSoup(html, 'lxml')** and **title=**...
put:

> #title tag don't show name of ep anymore so find it in h4 tag
> serie_name = unidecode(unicode(soup.title.string)).replace('Crunchyroll - Watch ','').replace('- Regarder sur Crunchyroll','').replace('/',' - ').replace(':','-').replace('?','.').replace('"','\'').replace("*", " ").replace("|","-")
> soup2 = BeautifulSoup(html, 'html.parser')
> ep_name=unidecode(unicode(soup2.find(id="showmedia_about_name").string)).replace('Crunchyroll - Watch ','').replace('- Regarder sur Crunchyroll','').replace('/',' - ').replace(':','-').replace('?','.').replace('"','\'').replace("*", " ").replace("|","-")
> ep_name=ep_name[1:]; ep_name=ep_name[:-1] # remove first and last '
> title=serie_name+'- '+ep_name


```

**Comment by Teredic** [comment]
Hi onimk,

i have tried your code but i just can't make it work. Because i don't have the "soup = BeautifulSoup(html, 'lxml') and title=..." line

I have tried in the end, replace some similar code, but no success.

Could you give me the exact line number to change/add that stuff ? Ty.

**Comment by Askadelion** [comment]
hi the code work fine, u must search the line 47 in decode.py
`title = re.findall('<title>(.+?)</title>', html)[0].replace....`

this u can find over the line
`if len(os.path.join('export', title+'.ass')) > 255:`

i have change the line to


```
# title = re.findall('<title>(.+?)</title>', html)[0].replace('Crunchyroll - Watch ', '')
soup = BeautifulSoup(html, 'html.parser')
serie_name = unidecode(unicode(soup.title.string)).replace(' - Watch on Crunchyroll', '')
ep_name=unidecode(unicode(soup.find(id="showmedia_about_name").string))
ep_name=ep_name[1:]; ep_name=ep_name[:-1] # remove first and last '
title=serie_name+' - '+ep_name`
```

and the same in the ultimate.py on line 228

then work it fine ;)

**Comment by Teredic** [comment]
ty.  I had some indent errors but was able to fix it.

However, i have another error now.

It's :

```
crunchy-xml-decoder\ultimate.py:245: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded
string will likely have unexpected results.
  title = unidecode(pattern.sub(lambda m: rep[re.escape(m.group(0))], title))
```

**Comment by Askadelion** [comment]
ahh... change this
`title = unidecode(pattern.sub(lambda m: rep[re.escape(m.group(0))], title))`
to 
`title = pattern.sub(lambda m: rep[re.escape(m.group(0))], title)`

**Comment by Teredic** [comment]
It worked ! Ty !

It looks likes there are no error anymore. I'll try some downloads, and if it's ok i'll close the issue.
