### ISSUE TITLE
Doesn't download anymore

### ISSUE THREAD

**Issue by Limitless99** [jaw20/Crunchyroll-XML-Decoder#6]
Hello there,

Today, Crunchyroll's servers went down for few hours. I believe they have updated the interface or something else that causes the problem of not downloading anymore.

I'm getting this message:

> Booting up...
> 
> Downloading 2 minute preview.
> Traceback (most recent call last):
>   File "C:\Users\A\Desktop\Anime\mobile-suit-gundam-iron-blooded-orphans\crunchy-xml-decoder.py", line 369, in <module>
>     makechoise()
>   File "C:\Users\A\Desktop\Anime\mobile-suit-gundam-iron-blooded-orphans\crunchy-xml-decoder.py", line 317, in makechoise
>     queueu('.\\queue.txt')
>   File "C:\Users\A\Desktop\Anime\mobile-suit-gundam-iron-blooded-orphans\crunchy-xml-decoder.py", line 106, in queueu
>     ultimate.ultimate(line.rstrip('\n'), '', '')
>   File "crunchy-xml-decoder\ultimate.py", line 263, in ultimate
>     media_id = xmlconfig.media_id.string
> AttributeError: 'NoneType' object has no attribute 'string'

**Comment by jaw20** [comment]
Ok, I have been investigating this for the past few days, and it may be the crunchyroll updated their video player. I'm currently trying to find the new link for the player.

**Comment by Limitless99** [comment]
Thanks @jaw20 

By the way, don't you think that the code you have in your repository is the older one? 
Isn't the newest one where HLS videos are encoded to flv. instead of ts.?
This old version here makes the output Bit rate worse.

**Comment by jaw20** [comment]
I'm pretty sure that after a week, videos move from rtmp to hls. rtmp is when the file is download as an flv. It probably has something to do with crunchyroll themselves.
