### ISSUE TITLE
CSRF token not found

### ISSUE THREAD

**Issue by anacros** [jaw20/Crunchyroll-XML-Decoder#9]
Ran into same issues of downloads not working using einstein's version, so tried yours. 
Ran into the following issue after entering login and password information:

"CSRF token not found"

Any suggestions? Or another issue due to CR changing their code? Tried finding solutions online, but can;t find associated filed they reference in the packet.

**Comment by jaw20** [comment]
I'm currently debugging the issue.

**Comment by Kcchouette** [comment]
To my mind, `CSRF` is something related to the cloudflare problem (so #6 )

**Comment by jaw20** [comment]
Fixed with #8
